version: "3.7"
services:

  jobrunner-run:
    build: .
    image: ghcr.io/opensafely/job-runner:latest
    init: true
    restart: unless-stopped
    volumes:
      &jobrunner_volumes
      - type: bind
        source: ${OPENSAFELY_MEDIUM_PRIVACY_STORAGE_BASE}
        target: ${OPENSAFELY_MEDIUM_PRIVACY_STORAGE_BASE}
      - type: bind
        source: ${OPENSAFELY_HIGH_PRIVACY_STORAGE_BASE}
        target: ${OPENSAFELY_HIGH_PRIVACY_STORAGE_BASE}
      - type: bind
        source: //var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: job_runner_work_dir
        target: /work_dir
    command: python -m jobrunner.run

  jobrunner-sync:
    image: ghcr.io/opensafely/job-runner:latest
    init: true
    restart: unless-stopped
    # Re-use volume config from above
    volumes: *jobrunner_volumes
    command: python -m jobrunner.sync

volumes:
  job_runner_work_dir:
