version: "3.7"
services:

  jobrunner-run:
    build: .
    image: ghcr.io/opensafely/job-runner:latest
    init: true
    restart: unless-stopped
    env_file: .env
    environment:
      &jobrunner_environment
      # Working directory (see the volume mounts below)
      - WORK_DIR=/work_dir
    volumes:
      &jobrunner_volumes
      - type: bind
        source: ${MEDIUM_PRIVACY_STORAGE_BASE}
        target: ${MEDIUM_PRIVACY_STORAGE_BASE}
      - type: bind
        source: ${HIGH_PRIVACY_STORAGE_BASE}
        target: ${HIGH_PRIVACY_STORAGE_BASE}
      - type: bind
        source: //var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: job_runner_work_dir
        target: /work_dir
    command: python -m jobrunner.run

  jobrunner-sync:
    image: ghcr.io/opensafely/job-runner:latest
    init: true
    restart: unless-stopped
    # Re-use environment and volume config from above
    env_file: .env
    environment: *jobrunner_environment
    volumes: *jobrunner_volumes
    command: python -m jobrunner.sync

volumes:
  job_runner_work_dir:
