name: Tag repo; build and publish assets
on:
  push:

jobs:
  tag-new-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Debug files
        run: |
          ls -la
          pwd
      - name: Tag
        id: tag
        uses: salsify/action-detect-and-tag-new-version@v1
        with:
          version-command: |
            cat VERSION

  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    # Only on a tagged release
    needs: tag-new-version
    if: needs.tag-new-version.outputs.tag
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and publish
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: whoan
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: job-runner
        push_git_tag: true
