name: Publish a Docker image for version-2 testing
on:
  push:
    branches:
      - version-2

jobs:

  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and publish
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: docker
        password: "${{ secrets.OPENSAFELY_DOCKER_PASSWORD }}"
        registry: docker.opensafely.org
        image_name: job-runner-v2
        image_tag: latest
        build_extra_args: "--build-arg=pythonversion=3.8.3"
